# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyRxSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyRxSwiftTest
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MyRxSwiftTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyRxSwiftTestUITests' do
    # Pods for testing
  end

end
